title: Kuba Kuźma - Ruby on Rails and JavaScript Consultant, Programmer
email: kuba@jah.pl
description: Kuba Kuźma - Ruby on Rails and Javascript freelancer
baseurl: ""
url: "https://kubakuzma.com"
twitter_username: qoobaa
github_username: qoobaa
markdown: kramdown
