title: Kuba Kuźma - Senior Software Engineer
email: kuba@kubakuzma.com
description: Kuba Kuźma - Senior Software Engineer (Ruby, JavaScript, FinTech)
baseurl: ""
url: "https://kubakuzma.com"
twitter_username: qoobaa
github_username: qoobaa
markdown: kramdown
